- platform: kodi
  name: BedroomKodi
  host: 192.168.1.116
- platform: kodi
  host: 192.168.1.120
  name: LivingRoomKodi
- platform: yamaha
  host: 192.168.1.110
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
