- platform: broadlink
  host: 192.168.1.105
  mac: 'B4:43:0D:FC:05:1D'
  type: rm_mini
  switches:
    tv:
      friendly_name: "Samsung 40inch"
      #command_on: "JgAYAZKUETgROBE4ERQRExEUERMRFBE4ETgROBEUERQRExEUERMRFBE4ERQRExEUERMRFBETETkRExE4ETkQORE4ETgROBEABgGSkxE4ETgRORETERQRExEUERMSOBE4ETgRExITERQRExEUERMRORETERQRExEUERMRFBE4ERQROBE2EzgROB$"
      #command_off: "JgAYAZKUETgROBE4ERQRExEUERMRFBE4ETgROBEUERQRExEUERMRFBE4ERQRExEUERMRFBETETkRExE4ETkQORE4ETgROBEABgGSkxE4ETgRORETERQRExEUERMSOBE4ETgRExITERQRExEUERMRORETERQRExEUERMRFBE4ERQROBE2EzgRO$"
    chuwi:
      friendly_name: "Chuwi"
      command_on: "JgBcAJSOEhIQNhETEDcRExA2ERMQEpGRERMSNBMREDYRFBA2ERMQE5CREBQQNhETEDYSEhA3EhIQEpGQExERNhETEDYSEhA3EBMREpGQEhIQNxISEDYSEhA2ExEQAA0FAAAAAAAAAAAAAAAA"
      command_off: "JgBcAJSOEhIQNhETEDcRExA2ERMQEpGRERMSNBMREDYRFBA2ERMQE5CREBQQNhETEDYSEhA3EhIQEpGQExERNhETEDYSEhA3EBMREpGQEhIQNxISEDYSEhA2ExEQAA0FAAAAAAAAAAAAAAAA"
